### ISSUE TITLE
Everyone sees Calendar even if I "Configure Simple Calendar" for a specific group

### ISSUE THREAD

**Issue by amvigil** [AndreyVMarkelov/mailru-jira-plugins-simplecal#4]
Im using Jira v5.0.6 and Jira v5.2.2 and I want to restrict the use of the calendar (to some groups). I "Configure Simple Calendar" for a specific groups (in both Jira servers), then logout and still everyone logged can see and create calendars.

**Comment by AndreyVMarkelov** [comment]
1 day to fix

**Comment by AndreyVMarkelov** [comment]
Done
